library(devtools)
use_git()
use_github()

(x <- "alfa,bravo,charlie,delta")

strsplit(x, split = ",")

unlist(strsplit(x, split = ","))

strsplit(x, split = ",")[[1]]

strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}
use_r("strsplit1")

load_all()

(x <- "alfa,bravo,charlie,delta")
strsplit1(x, split = ",")
exists("strsplit1", where = globalenv(), inherits = FALSE)

check()
use_mit_license()
check()

library(roxygen2)
document()

?strsplit1



# Generated by roxygen2: do not edit by hand
export(strsplit1)



install()
library(day5)
x <- "alfa,bravo,charlie,delta"
strsplit1(x, split = ",")

use_testthat()
use_test("strsplit1")
test_that("strsplit1() splits a string", {
  expect_equal(strsplit1("a,b,c", split = ","), c("a", "b", "c"))
})

test()

use_package("stringr")
stringr::fun()

str_split_one <- function(string, pattern, n = Inf) {
  stopifnot(is.character(string), length(string) <= 1)
  if (length(string) == 1) {
    stringr::str_split(string = string, pattern = pattern, n = n)[[1]]
  } else {
    character()
  }
}
load_all()
x <- "alfa,bravo,charlie,delta"
str_split_one(x, pattern = ",")

rename_files("strsplit1", "str_split_one")

test_that("str_split_one() splits a string", {
  expect_equal(str_split_one("a,b,c", ","), c("a", "b", "c"))
})

test_that("str_split_one() errors if input length > 1", {
  expect_error(str_split_one(c("a,b","c,d"), ","))
})

test_that("str_split_one() exposes features of stringr::str_split()", {
  expect_equal(str_split_one("a,b,c", ",", n = 2), c("a", "b,c"))
  expect_equal(str_split_one("a.b", stringr::fixed(".")), c("a", "b"))
})

document()

load_all()
str_split_one("a, b, c", pattern = ", ")


vector <- c("a", "b", "c")
# Using replace()
new_vector <- replace(vector, vector == "a", 1)
new_vector <- replace(new_vector, vector == "b", 2)
new_vector <- replace(new_vector, vector == "c", 3)
# Result
print(new_vector)




