library(devtools)
use_git()
use_github()

(x <- "alfa,bravo,charlie,delta")

strsplit(x, split = ",")

unlist(strsplit(x, split = ","))

strsplit(x, split = ",")[[1]]

strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}
use_r("strsplit1")

load_all()

(x <- "alfa,bravo,charlie,delta")
strsplit1(x, split = ",")
exists("strsplit1", where = globalenv(), inherits = FALSE)

check()
use_mit_license()
check()

library(roxygen2)
document()

?strsplit1



# Generated by roxygen2: do not edit by hand
export(strsplit1)



install()
library(day5)
x <- "alfa,bravo,charlie,delta"
strsplit1(x, split = ",")

use_testthat()
use_test("strsplit1")
test_that("strsplit1() splits a string", {
  expect_equal(strsplit1("a,b,c", split = ","), c("a", "b", "c"))
})

test()

use_package("stringr")
stringr::fun()

str_split_one <- function(string, pattern, n = Inf) {
  stopifnot(is.character(string), length(string) <= 1)
  if (length(string) == 1) {
    stringr::str_split(string = string, pattern = pattern, n = n)[[1]]
  } else {
    character()
  }
}











